#!/usr/bin/env python
import os

env = SConscript("godot-cpp/SConstruct")
env.Append(CCFLAGS=['-fexceptions'])

sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    target="../addons/hexasphere_generator/bin/hexasphere",
    source=sources,
)

Default(library)
